language: node_js

node_js:
  - "0.12"

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver

script:
  - grunt
  # removed as we don't have tests yet and karma fails without tests, bug is fixed with v1.0
  #- grunt test
  - grunt coveralls:karma_tests
